In [2]:
import numpy as np

## Exercise 7.2

In [10]:
# 1)

def logistic(t):
  return 1/(1 + np.exp(-t))

# 2)

print("2)")
print(logistic(-np.log(2)), logistic(0), logistic(np.log(2)))
print()

# 3)

def softmax(v):
  exps = np.exp(v)
  sum = np.sum(exps)
  return exps / sum

# 4)

print("4)")
for _ in range(5):
  rand_array = np.random.rand(3) * 10 - 5
  print(rand_array)
  sm = softmax(rand_array)
  print(sm)
  print(np.sum(sm))
  print()

# 5)
print("5)")
for _ in range(5):
  rand_number = np.random.rand() * 10 - 5
  print("logistic = ", logistic(rand_number))
  print("softmax = ", softmax([0, rand_number]))
  print()


2)
0.3333333333333333 0.5 0.6666666666666666

4)
[3.76012478 0.35435113 2.29486791]
[0.79101422 0.02624675 0.18273903]
1.0

[-1.30888961  1.92437943 -1.26038714]
[0.0364802  0.92522661 0.03829319]
1.0

[-1.39565464  3.70277534 -2.07938885]
[0.00605073 0.99089529 0.00305398]
1.0

[-3.81746263  2.06495751  3.1646061 ]
[6.95981100e-04 2.49631884e-01 7.49672135e-01]
1.0

[-4.93056645  2.02174714 -3.90190792]
[9.52958848e-04 9.96381319e-01 2.66572207e-03]
1.0

5)
logistic =  0.9843817227779923
softmax =  [0.01561828 0.98438172]

logistic =  0.9923663603781654
softmax =  [0.00763364 0.99236636]

logistic =  0.008844234118521779
softmax =  [0.99115577 0.00884423]

logistic =  0.967125070202247
softmax =  [0.03287493 0.96712507]

logistic =  0.021766400487595573
softmax =  [0.9782336 0.0217664]



## Exercise 7.3

In [14]:
coef = np.array([[-0.85433652,  2.74057947,  0.41217626]])

log_odds = coef @ np.array([1, 1, 1])
print(log_odds)

# 1)
probability = logistic(log_odds)
print(probability)

# 2)
print(probability >= .5)

[2.29841921]
[0.90874603]
[ True]


## Exercise 7.4

In [ ]:
coef = np.array([[ 0.95978307, -0.36742618, -0.05523787],
       [-1.04501035,  0.25190438,  0.39008223],
       [ 0.08522728,  0.1155218,  -0.33484436]])

log_odds = coef @ np.array([1, 1, 1])
print(log_odds)

# 1)
probabilities = softmax(log_odds)
print(probabilities)

# 2)
print(probabilities.argmax())

[ 0.53711902 -0.40302374 -0.13409528]
[0.52585645 0.20538484 0.2687587 ]
0
