In [2]:
import numpy as np

## Exercise 7.2

In [ ]:
# 1)

def logistic(t):
  return 1/(1 + np.exp(-t))

# 2)

print("2)")
print(logistic(-np.log(2)), logistic(0), logistic(np.log(2)))
# Alt: print(logistic(np.array([-np.log(2), 0, np.log(2)])))
print()

# 3)

def softmax(v):
  exps = np.exp(v)
  sum = np.sum(exps)
  return exps / sum

# 4)

print("4)")
for _ in range(5):
  rand_array = np.random.rand(3) * 10 - 5 # Random array: 3 elements from -5 to 5
  print(rand_array)
  sm = softmax(rand_array)
  print(sm)
  print(np.sum(sm))
  print()

# 5)
print("5)")
for _ in range(5):
  rand_number = np.random.rand() * 10 - 5
  print("logistic = ", logistic(rand_number))
  print("softmax = ", softmax([0, rand_number]))
  print()


2)
0.3333333333333333 0.5 0.6666666666666666
[0.33333333 0.5        0.66666667]

4)
[-1.47927418 -3.47643156 -0.39486703]
[0.24429532 0.03315589 0.72254879]
1.0

[ 0.98009065 -4.67437141  2.50209587]
[1.79054088e-01 6.27021701e-04 8.20318890e-01]
1.0

[-4.20395609  1.07803173 -1.2249845 ]
[0.00459922 0.90494526 0.09045552]
1.0000000000000002

[-1.3667947  -0.07496606 -2.61290716]
[0.20296094 0.73866328 0.05837578]
1.0

[4.84029725 3.15114571 4.42161496]
[0.54271453 0.10022643 0.35705904]
1.0

5)
logistic =  0.7462550408469308
softmax =  [0.25374496 0.74625504]

logistic =  0.3558166838495712
softmax =  [0.64418332 0.35581668]

logistic =  0.9843836741792901
softmax =  [0.01561633 0.98438367]

logistic =  0.9089187110525762
softmax =  [0.09108129 0.90891871]

logistic =  0.20603175302592866
softmax =  [0.79396825 0.20603175]



## Exercise 7.3

In [14]:
coef = np.array([[-0.85433652,  2.74057947,  0.41217626]])

log_odds = coef @ np.array([1, 1, 1])
print(log_odds)

# 1)
probability = logistic(log_odds)
print(probability)

# 2)
print(probability >= .5)

[2.29841921]
[0.90874603]
[ True]


## Exercise 7.4

In [ ]:
coef = np.array([[ 0.95978307, -0.36742618, -0.05523787],
       [-1.04501035,  0.25190438,  0.39008223],
       [ 0.08522728,  0.1155218,  -0.33484436]])

log_odds = coef @ np.array([1, 1, 1])
print(log_odds)

# 1)
probabilities = softmax(log_odds)
print(probabilities)

# 2)
print(probabilities.argmax())

[ 0.53711902 -0.40302374 -0.13409528]
[0.52585645 0.20538484 0.2687587 ]
0
