Udvalgte løsninger fra lektion 2

In [1]:
import numpy as np

In [2]:
B = np.array([
    [7, -5, 1],
    [1, -4, -3],
    ])

D = np.array([[3, 5], [-1, 4]])

np.matmul(D, B)

array([[ 26, -35, -12],
       [ -3, -11, -13]])

In [3]:
E = np.array([[-5],[3]])
C = np.array([[1, 2], [-2, 1]])
np.matmul(E, C)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [6]:
A = np.array([
    [3, -6],
    [-1, 2]
])

B = np.array([
    [-1, 1],
    [3, 4],
])

C = np.array([
    [-3, -5],
    [2, 1],
])

print(np.matmul(A, B))
print(np.matmul(A, C))


[[-21 -21]
 [  7   7]]
[[-21 -21]
 [  7   7]]


In [8]:
np.linalg.inv(A)

LinAlgError: Singular matrix